### ISSUE TITLE
Item Duplicates

### ISSUE THREAD

**Issue by VI269** [VI269/NeverWinterDays#8]

**Comment by VI269** [comment]
In branch VI269-Shop the object.menu() function doesn't work. @Kliche-1 look into it please.

**Comment by Kliche-1** [comment]
Hello Vedant maybe trying changing the object.menu() function without the . in the middle since that could lead to an unexpected syntax error

**Comment by VI269** [comment]
The problem is in the class Shop. I don't think that will work well. Check the code.

**Comment by VI269** [comment]
@Kliche-1 did you see the code? Could you find a way to fix it?

**Comment by Kliche-1** [comment]
Im checking now wait. I'll see if I can do anything.

**Comment by VI269** [comment]
Nevermind Resolved It
